name = "xlorpaste-worker"

compatibility_date = "2022-7-27"

workers_dev = true
route = "xlorpaste-worker.yjl9903.workers.dev/*"

entry-point = ".output/server/index.mjs"

[[kv-namespaces]]
binding = "XLORPASTE"
id = "4cb100568fb84072ba819d668aea818d"
preview_id = "c6aa0006430a4f82911c6afceaa06e17"

[build]
command = ""

[env.production]
zone_id = "0a23e291021e56440c9d1d8fa29e3fed"
route = "paste.cpany.dev/*"
# zone_id = "d46a34c01748b72153a78669c137092d"
# route = "api.xlorpaste.cn/*"
