name = "xlorpaste-worker"
type = "javascript"

workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-12-24"

[build]
command = "npm install; npx pnpm run build"
[build.upload]
format = "service-worker"
