name: Build

on:
  push:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          
      - run: pnpm install
      
      - run: pnpm run build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/app/dist
          
      - uses: manyuanrong/setup-ossutil@v3.0
        with:
          endpoint: ${{ secrets.ACCESS_ENDPOINT }}
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}

      - name: Deploy To OSS
        run: |
          ossutil rm oss://${{ secrets.BUCKET_NAME }}/ -rf
          ossutil cp ./packages/app/dist oss://${{ secrets.BUCKET_NAME }}/ -rf

  IntelliJ:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Build
        working-directory: ./IntelliJ
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew test
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: IntelliJ-plugin
          path: ./IntelliJ/build/distributions/
