name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build worker
        run: pnpm build:worker
        env:
          NITRO_PRESET: cloudflare

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: ./packages/worker
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: 7cbfb60ad7052f0d8cf590a51e024987
